export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const COMPANY_USER_BEGIN = 'COMPANY_USER_BEGIN';
export const COMPANY_USER_SUCCESS = 'COMPANY_USER_SUCCESS';
export const COMPANY_USER_FAIL = 'COMPANY_USER_FAIL';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';